GestionBUT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('student/', include("student.urls")),
    path('professor/', include("professor.urls")),
    path('administrator/', include("administrator.urls")),
]

urlpatterns += staticfiles_urlpatterns()

administrator/urls.py
from django.urls import path
from administrator.views import *

app_name = 'administrator'

urlpatterns = [
    # http://domain/administrator/
    path('', index, name="index"),

    # http://domain/administrator/createEstablishment/ (no template)
    path('createEstablishment/', createEstablishment, name="createEstablishment"),

    # http://domain/administrator/establishment/1/
    path('establishment/<establishment_id>/', establishment, name="establishment"),
    # http://domain/administrator/establishment/1/createDepartment/ (no template)
    path('establishment/<establishment_id>/createDepartment/', createDepartment, name="createDepartment"),
    #http://domain/administrator/establishment/1/department/1/
    path('establishment/<establishment_id>/department/<department_id>/', department, name="department"),


    # http://domain/administrator/establishment/1/department/1/createCompetence/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/createCompetence/', createCompetence, name="createCompetence"),
    # http://domain/administrator/establishment/1/department/1/editCompetence/1/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/editCompetence/<competence_id>/', editCompetence, name="editCompetence"),
    # http://domain/administrator/establishment/1/department/1/deleteCompetence/1/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/deleteCompetence/<competence_id>/', deleteCompetence, name="deleteCompetence"),


    # http://domain/administrator/establishment/1/department/1/createSemester/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/createSemester/', createSemester, name="createSemester"),
    # http://domain/administrator/establishment/1/department/1/editSemester/1/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/editSemester/<semester_id>/', editSemester, name="editSemester"),
    # http://domain/administrator/establishment/1/department/1/deleteSemester/1/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/deleteSemester/<semester_id>/', deleteSemester, name="deleteSemester"),


    # http://domain/administrator/establishment/1/department/1/createGroup (no template)
    path('establishment/<establishment_id>/department/<department_id>/createGroup', createGroup, name="createGroup"),
    # http://domain/administrator/establishment/1/department/1/editGroup/1/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/editGroup/<group_id>/', editGroup, name="editGroup"),
    # http://domain/administrator/establishment/1/department/1/deleteGroup/1/ (no template)
    path('establishment/<establishment_id>/department/<department_id>/deleteGroup/<group_id>/', deleteGroup, name="deleteGroup"),
]

main/urls.py
from django.urls import path
from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name="index"),
]

administrator/models.py
from django.db import models

# Create your models here.

administrator/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from main.models import *
from main.views import isAdministrator

@login_required
def index(request):

    # Auth security
    if isAdministrator(request.user) == None:
        return redirect("main:index")

    # Method body
    administrator_view = {}
    establishments = Establishment.objects.all()
    for establishment in establishments:
        administrator_view[establishment] = establishment.getDepartments()

    return render(
        request,
        "a_index.html",
        context = {
            "administrator_view" : administrator_view,
        }
    )

@login_required
def establishment(request, establishment_id):

    # Auth security
    if isAdministrator(request.user) == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    if establishment == None:
        return redirect("administrator:index")

    # Method body
    administrator_view = {}
    for department in establishment.getDepartments():
        administrator_view[department] = department.getSemesters()

    return render(
        request,
        "a_establishment.html",
        context= {
            "establishment": establishment,
            "administrator_view": administrator_view
        }
    )

@login_required
def createEstablishment(request):
    # Auth security
    if isAdministrator(request.user) == None or request.method != "POST":
        return redirect("main:index")

    # Method body
    post = request.POST
    if "name" in post:
        name = post.get("name")
        if name != "":
            establishment = Establishment(name=name)
            establishment.save()
            if "it_department" in post:
                establishment.createITDepartment()

    return redirect("administrator:index")

@login_required
def department(request, establishment_id, department_id):

    # Auth security
    if isAdministrator(request.user) == None:
        return redirect("login")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None:
        return redirect("administrator:establishment", establishment.id)

    # Method body
    administrator_view = {}
    for department in establishment.getDepartments():
        administrator_view[department] = department.getSemesters()

    return render(
        request,
        "a_department.html",
        context= {
            "establishment": establishment,
            "department": department,
            "administrator_view": administrator_view,
        }
    )


@login_required
def createDepartment(request, establishment_id):

    # Auth security
    if isAdministrator(request.user) == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    if establishment == None or request.method != "POST":
        return redirect("administrator:index")

    # Method body
    post = request.POST
    if "name" in post and "min_competence_grade" in post and "min_competence_required" in post:
        name = post.get("name")
        str_min_competence_grade = post.get("min_competence_grade")
        str_min_competence_required = post.get("min_competence_required")
        if "it_department" in post:
            establishment.createITDepartment()
        elif name != "":
            department = Department(name=name, establishment=establishment, min_competence_grade=int(str_min_competence_grade), min_competence_required=int(str_min_competence_required))
            department.save()

    return redirect("administrator:establishment", establishment_id=establishment.id)

@login_required
def createCompetence(request, establishment_id, department_id):

    # Auth security
    if isAdministrator(request.user) == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None or request.method != "POST":
        return redirect("administrator:establishment", establishment_id)

    # Method body
    post = request.POST
    if "name" in post and "number" in post:
        name = post.get("name")
        str_number = post.get("number")
        competence = Competence(department=department, number=int(str_number), name=name)
        if "description" in post:
            description = post.get("description")
            if description != "":
                competence.description = description
        competence.save()

    return redirect("administrator:department", establishment_id, department_id)

@login_required
def editCompetence(request, establishment_id, department_id, competence_id):

    # Auth security
    if isAdministrator(request.user) == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    competence = Competence.objects.get(id=competence_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None or competence == None:
        return redirect("administrator:establishment", establishment_id)

    # Method body
    post = request.POST
    if  "number" in post and "name" in post and "description" in post:
        str_number = post.get("number")
        name = post.get("name")
        description = post.get("description")
        competence.number = int(str_number)
        competence.name = name
        competence.description = description
        competence.save()

    return redirect("administrator:department", establishment_id, department_id)

@login_required
def deleteCompetence(request, establishment_id, department_id, competence_id):

    # Auth security
    if isAdministrator(request.user) == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    competence = Competence.objects.get(id=competence_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None or competence == None:
        return redirect("administrator:establishment", establishment_id)

    # Method body
    competence.delete()

    return redirect("administrator:department", establishment_id, department_id)






@login_required
def createSemester(request, establishment_id, department_id):

    # Auth security
    admin = isAdministrator(request.user)
    if admin == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None or request.method != "POST":
        return redirect("administrator:establishment", establishment_id)

    # Method body
    post = request.POST
    if "number" in post:
        str_number = post.get("number")
        semester = Semester(department=department, number=int(str_number))
        semester.save()

    return redirect("administrator:department", establishment_id, department_id)

@login_required
def editSemester(request, establishment_id, department_id, semester_id):

    # Auth security
    admin = isAdministrator(request.user)
    if admin == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    semester = Semester.objects.get(id=semester_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None or semester == None:
        return redirect("administrator:establishment", establishment_id)

    # Method body
    post = request.POST
    if "number" in post:
        str_number = post.get("number")
        semester.number = int(str_number);
        semester.save()

    return redirect("administrator:department", establishment_id, department_id)

@login_required
def deleteSemester(request, establishment_id, department_id, semester_id):

    # Auth security
    admin = isAdministrator(request.user)
    if admin == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    semester = Semester.objects.get(id=semester_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None or semester == None:
        return redirect("administrator:establishment", establishment_id)

    # Method body
    semester.delete()

    return redirect("administrator:department", establishment_id, department_id)







@login_required
def createGroup(request, establishment_id, department_id):

    # Auth security
    admin = isAdministrator(request.user)
    if admin == None:
        return redirect("main:index")

    # Query parameters
    establishment = Establishment.objects.get(id=establishment_id)
    department = Department.objects.get(id=department_id)
    if establishment == None:
        return redirect("administrator:index")
    elif department == None or request.method != "POST":
        return redirect("administrator:establishment", establishment_id)

    # Method body
    post = request.POST
    if "name" in post and "parent" in post:
        print(post)
        name = post.get("name")
        str_parent = post.get("parent")

administrator/templates/a_department.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <div class="history">
        <a href="{% url 'administrator:establishment' establishment_id=establishment.id %}"> < </a>
    </div>

    {% for competence in department.getCompetences %}
    <div class="modal {{ competence.id }} competence">
        <div class="modal-content">
            <h1>Modifier une compétence</h1>
            <div class="modal-content-header">
                <h2>{{ competence }}</h2>
                <form action="{% url 'administrator:deleteCompetence' establishment_id=department.establishment.id department_id=department.id competence_id=competence.id %}" method="post">
                    {% csrf_token %}
                    <button class="delete-button hoverable">Supprimer</button>
                </form>
            </div>
            <form action="{% url 'administrator:editCompetence' establishment_id=department.establishment.id department_id=department.id competence_id=competence.id %}" method="post">
                {% csrf_token %}
                <div class="datas">
                    <div class="data">
                        <div class="input">
                            <label for="number">Numéro de la compétence</label>
                            <input type="number" name="number" id="number" value="{{ competence.number }}" required>
                        </div>
                        <div class="input">
                            <label for="name">Nom de la compétence</label>
                            <input type="text" name="name" id="name" value="{{ competence.name }}" required>
                        </div>
                        <div class="input">
                            <label for="description">Description de la compétence</label>
                            <textarea name="description" id="description" value="{{ competence.description }}" cols="30" rows="10"></textarea>
                        </div>
                    </div>
                    <div class="data">
                        <div class="ues">
                            <h2>UEs</h2>
                        </div>
                    </div>
                </div>
                <div class="button-container">
                    <button class="modal-button hoverable">Modifier</button>
                </div>
            </form>
        </div>
    </div>
    {% endfor %}


    {% for semester in department.getSemesters %}
    <div class="modal {{ semester.id }} semester">
        <div class="modal-content">
            <h1>Modifier un semestre</h1>
            <div class="modal-content-header">
                <h2>{{ semester }}</h2>
                <form action="{% url 'administrator:deleteSemester' establishment_id=department.establishment.id department_id=department.id semester_id=semester.id %}" method="post">
                    {% csrf_token %}
                    <button class="delete-button hoverable">Supprimer</button>
                </form>
            </div>
            <form action="{% url 'administrator:editSemester' establishment_id=department.establishment.id department_id=department.id semester_id=semester.id %}" method="post">
                {% csrf_token %}
                <div class="datas">
                    <div class="data">
                        <div class="input">
                            <label for="number">Numéro du semestre</label>
                            <input type="number" name="number" id="number" value="{{ semester.number }}" required>
                        </div>
                    </div>
                    <div class="data">
                        <div class="resources">
                            <h2>Ressources</h2>
                        </div>
                    </div>
                </div>
                <div class="button-container">
                    <button class="modal-button hoverable">Modifier</button>
                </div>
            </form>
        </div>
    </div>
    {% endfor %}


    {% for group in department.getGroups %}
    <div class="modal {{ group.id }} group">
        <div class="modal-content">
            <h1>Modifier un groupe</h1>

            <div class="modal-content-header">
                <h2>{{ group }}</h2>
                <form action="{% url 'administrator:deleteGroup' establishment_id=department.establishment.id department_id=department.id group_id=group.id %}" method="post">
                    {% csrf_token %}
                    <button class="delete-button hoverable">Supprimer</button>
                </form>
            </div>
            <form action="{% url 'administrator:editGroup' establishment_id=department.establishment.id department_id=department.id group_id=group.id %}" class="form" method="post">
                {% csrf_token %}
                <div class="datas">
                    <div class="data">
                        <div class="input">
                            <label for="name">Nom du groupe</label>
                            <input type="text" name="name" id="name" value="{{ group.name }}" required>
                        </div>
                        <div class="input">
                            <label for="parent">Groupe parent</label>
                            <select name="parent" id="parent">
                                <option value="none">Aucun</option>
                                {% for sub_group in department.getGroups %}
                                {% if sub_group.id != group.id %}
                                <option value="{{ sub_group.id }}" {% if group.parent.id == sub_group.id %}selected{% endif %}>{{ sub_group.name }}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="data">
                        <div class="students">
                            <h2>Etudiants</h2>
                        </div>
                    </div>
                </div>
                <div class="button-container">
                    <button class="modal-button hoverable">Modifier</button>
                </div>
            </form>
        </div>
    </div>
    {% endfor %}


    <div class="modal add_competence">
        <div class="modal-content">
            <h1>Ajouter une compétence</h1>
            <form action="{% url 'administrator:createCompetence' establishment_id=department.establishment.id department_id=department.id %}" method="post">
                {% csrf_token %}
                <div class="datas">
                    <div class="data">
                        <div class="input">
                            <label for="number">Numéro de la compétence</label>
                            <input type="number" name="number" id="number" required>
                        </div>
                        <div class="input">
                            <label for="name">Nom de la compétence</label>
                            <input type="text" name="name" id="name" required>
                        </div>
                        <div class="input">
                            <label for="description">Description de la compétence</label>
                            <textarea name="description" id="description" cols="30" rows="10"></textarea>
                        </div>
                    </div>
                    <div class="data">
                        <div class="ues">
                            <h2>UEs</h2>
                        </div>
                    </div>
                </div>
                <div class="button-container">
                    <button class="establishment-button hoverable">Ajouter</button>
                </div>
            </form>
        </div>
    </div>
    <div class="modal add_semester">
        <div class="modal-content">
            <h1>Ajouter un semestre</h1>
            <form action="{% url 'administrator:createSemester' establishment_id=department.establishment.id department_id=department.id %}" method="post">
                {% csrf_token %}
                <div class="datas">
                    <div class="data">
                        <div class="input">
                            <label for="number">Numéro du semestre</label>
                            <input type="number" name="number" id="number" required>
                        </div>
                    </div>
                    <div class="data">
                        <div class="resources">
                            <h2>Ressources</h2>
                        </div>
                    </div>
                </div>
                <div class="button-container">
                    <button class="establishment-button hoverable">Ajouter</button>
                </div>
            </form>
        </div>
    </div>
    <div class="modal add_group">
        <div class="modal-content">
            <h1>Ajouter un groupe</h1>
            <form action="{% url 'administrator:createGroup' establishment_id=department.establishment.id department_id=department.id %}" method="post">
                {% csrf_token %}
                <div class="datas">
                    <div class="data">
                        <div class="input">
                            <label for="name">Nom du groupe</label>
                            <input type="text" name="name" id="name" required>
                        </div>
                        <div class="input">
                            <label for="parent">Groupe parent</label>
                            <select name="parent" id="parent">
                                <option value="none">Aucun</option>
                                {% for group in department.getGroups %}
                                <option value="{{ group.id }}">{{ group.name }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="data">
                        <div class="students">
                            <h2>Etudiants</h2>
                        </div>
                    </div>
                </div>
                <div class="button-container">
                    <button class="establishment-button hoverable">Ajouter</button>
                </div>
            </form>
        </div>
    </div>

    <div class="content">
        <h2>Liste des Competences</h2>
        <div class="carousel-container styled-card">
            <div class="carousel">
                {% for competence in department.getCompetences %}
                <div class="competence {{ competence.id }} carousel-item styled-card hoverable">
                    <h2 class="middle">{{ competence }}</h2>
                    <p>{{ competence.name }}</p>
                </div>
                {% endfor %}
                <div id="add_competence" class="carousel-item plus styled-card hoverable">+</div>
            </div>
        </div>
        <h2>Liste des Semestres</h2>
        <div class="carousel-container styled-card">
            <div class="carousel">
                {% for semester in department.getSemesters %}
                <div class="semester {{ semester.id }} carousel-item styled-card hoverable">
                    <h2 class="middle">{{ semester }}</h2>
                    <p>{{ semester.resourceCount }} ressources</p>
                </div>
                {% endfor %}
                <div id="add_semester" class="carousel-item plus styled-card hoverable">+</div>
            </div>
        </div>
        <h2>Liste des Groupes</h2>
        <div class="carousel-container styled-card">
            <div class="carousel">
                {% for group in department.getGroups %}
                <div class="group {{ group.id }} carousel-item styled-card hoverable">
                    <h2 class="middle">{{ group }}</h2>
                    <p>{{ group.studentCount }} étudiants</p>
                </div>
                {% endfor %}
                <div id="add_group" class="carousel-item plus styled-card hoverable">+</div>
            </div>
        </div>
    </div>
</div>

<aside>
    <div class="aside-container styled-card">
        <div class="links">
            <h3>Liens utiles</h3>
            {% if not usefulLinks %}
            Aucun liens utiles.
            {% else %}
            {% for link in department.getUsefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="{{ link.name }}" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</aside>

{% endblock %}

administrator/templates/a_establishment.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper">
    <div class="history">
        <a href="{% url 'administrator:index' %}"> < </a>
    </div>

    <div class="modal add_department">
        <div class="modal-content">
            <h2>Ajouter un Département</h2>
            <form action="{% url 'administrator:createDepartment' establishment_id=establishment.id %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <label for="name">Nom du département</label>
                    <input type="number" name="name" id="name">
                </div>
                <div class="input">
                    <label for="min_competence_required">Nombre minimal de compétence à valider</label>
                    <input type="number" name="min_competence_required" id="min_competence_required">
                </div>
                <div class="input">
                    <label for="min_competence_grade">Note minimale</label>
                    <input type="number" name="min_competence_grade" id="min_competence_grade">
                </div>
                <div class="input">
                    Liste des départements prédéfinis disponibles:
                    <ul>
                        <li>
                            <input type="checkbox" name="it_department" id="it_department">
                            <label for="it_department">Départment informatique</label>
                        </li>
                    </ul>
                </div>
                <button class="establishment-button hoverable">Ajouter</button>
            </form>
        </div>
    </div>

    <div class="content">
        <h2>Liste des départements de <strong>{{ establishment }}</strong></h2>
        <div class="departments">
            {% for department, semesters in administrator_view.items %}
            <div class="department styled-card hoverable">
                <form action="{% url 'administrator:department' establishment_id=establishment.id department_id=department.id %}"  class="auto establishment-form" method="post">
                    {% csrf_token %}
                    <h2>{{ department }}</h2>
                    <p>Nombre minimal de compétence à valider : {{ department.min_competence_required|default_if_none:"Non défini" }}</p>
                    <p>Note minimale d'une compétence : {{ department.min_competence_grade|default_if_none:"Non défini" }}</p>
                </form>
            </div>
            {% endfor %}
            <div id="add_department" class="department plus styled-card hoverable">+</div>
        </div>
    </div>
</div>

{% endblock %}

administrator/templates/a_index.html
{% extends 'head.html' %}
{% load static %}
{% block content %}
 
<div class="wrapper">
    <h1>Bonjour {{ user.last_name }} {{ user.first_name }} !</h1>

    <div class="modal add_establishment">
        <div class="modal-content">
            <h2>Ajouter un établissement</h2>
            <form action="{% url 'administrator:createEstablishment' %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <label for="name">Nom de l'établissement</label>
                    <input type="text" name="name" id="name" required>
                </div>
                <div class="input">
                    Liste des départements disponibles:
                    <ul>
                        <li>
                            <input type="checkbox" name="it_department" id="it_department">
                            <label for="it_department">Départment informatique</label>
                        </li>
                    </ul>
                </div>
                <button class="establishment-button hoverable">Ajouter</button>
            </form>
        </div>
    </div>

    <div class="content">
        <h2>Liste des établissements</h2>
        <div class="establishments">
            {% for establishment, departments in administrator_view.items %}
            <div class="establishment styled-card hoverable">
                <form action="{% url 'administrator:establishment' establishment_id=establishment.id %}"  class="auto" method="post">
                    {% csrf_token %}
                    <h2>{{ establishment.name }}</h2>
                    {% if not departments %}
                    <p>Aucun départment</p>
                    {% else %}
                    <div class="departments">
                        {% for department in departments %}
                        <div class="department styled-card">
                            <h2>{{ department }}</h2>
                            <p>Nombre de professeurs : {{ department.getProfessors|length }}</p>
                            <p>Nombre d'étudiants : {{ department.getStudents|length }}</p>
                        </div>
                        {% endfor %}
                    </div>
                    {% endif %}
                </form>
            </div>
            {% endfor %}
            <div id="add_establishment" class="establishment plus styled-card hoverable">+</div>
        </div>
    </div>
</div>

{% endblock %}