GestionBUT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('student/', include("student.urls")),
    path('professor/', include("professor.urls")),
    path('administrator/', include("administrator.urls")),
]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name="index"),
]

templates/head.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gestion de BUT</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}" media="all" />
    <script src="{% static 'js/script.js' %}" defer></script>

    {% if "/student/" in request.path %}
    <link rel="stylesheet" href="{% static 'css/student.css' %}" media="all" />
    <script src="{% static 'js/student.js' %}" defer></script>
    {% elif "/professor/" in request.path %}
    <link rel="stylesheet" href="{% static 'css/professor.css' %}" media="all" />
    <script src="{% static 'js/professor.js' %}" defer></script>
    {% elif "/administrator/" in request.path %}
    <link rel="stylesheet" href="{% static 'css/administrator.css' %}" media="all" />
    <script src="{% static 'js/administrator.js' %}" defer></script>
    {% endif %}

</head>

<body>
    <header>
        <nav>
            <form class="auto" action="{% url 'main:index' %}" method="post">
                {% csrf_token %}
                <span class="effect-underline">Gestion de BUT</span>
            </form>
            {% if user.is_authenticated %}
            <form class="auto" action="{% url 'profile' %}" method="post">
                {% csrf_token %}
                <span class="effect-underline">{{ user.last_name|upper }} {{ user.first_name|upper }}</span>
            </form>
            <form class="auto" action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <span class="effect-underline">Se déconnecter</span>
            </form>
            {% else %}
            <form class="auto" action="{% url 'login' %}" method="post">
                {% csrf_token %}
                <span class="effect-underline">Se connecter</span>
            </form>
            {% endif %}
        </nav>
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>