GestionBUT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('student/', include("student.urls")),
    path('professor/', include("professor.urls")),
    path('administrator/', include("administrator.urls")),
]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name="index"),
]

student/urls.py
from django.urls import path
from student.views import *

app_name = 'student'

urlpatterns = [
    # http://domain/student/
    path('', index, name="index"),

    # http://domain/1/student/resource/1/
    path('<semester_id>/resource/<resource_id>/', resource, name="resource"),

    # http://domain/1/student/ue/1/
    path('<semester_id>/ue/<ue_id>/', ue, name="ue"),
]

student/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from main.models import *
from main.views import isStudent

@login_required
def index(request):

    # Auth security
    user = request.user
    student = isStudent(user)
    if student == None:
        return redirect("login")

    department = student.department

    # Method body
    student_view = {}
    for semester in department.getSemesters():
        student_view[semester] = {}, {}

        # Resource view
        for resource in semester.getResources():
            student_view[semester][0][resource] = {}, resource.getNote(student), resource.getRanking(student)
            for evaluation in resource.getEvaluations():
                student_view[semester][0][resource][0][evaluation] = evaluation.getNote(student)

        # UE view
        for ue in semester.getUEs():
            student_view[semester][1][ue] = {}, ue.getNote(student), ue.getRanking(student)
            for resource in ue.getResources():
                student_view[semester][1][ue][0][resource] = {}
                for evaluation in resource.getEvaluations():
                    student_view[semester][1][ue][0][resource][evaluation] = evaluation.getNote(student)

    return render(
        request,
        "s_index.html",
        context = {
            "establishment": department.establishment,
            "student_view": student_view,
            "lastGrades": student.getLastGrades(5),
            "validate": department.validateYear(student),
            "usefulLinks": department.getUsefulLinks(),
        }
    )

@login_required
def resource(request, semester_id, resource_id):

    # Auth security
    user = request.user
    student = isStudent(user)
    if student == None:
        return redirect("login")

    # Query parameters
    semester = Semester.objects.filter(id=semester_id).first()
    resource = Resource.objects.filter(id=resource_id).first()
    if semester == None or resource == None:
        return redirect("student:index")

    # Method body
    student_view = {}
    for evaluation in resource.getEvaluations():
        student_view[evaluation] = (
            evaluation.getNote(student),
            evaluation.getRanking(student),
            evaluation.getAverage(),
            evaluation.getMax(),
            evaluation.getMin()
        )

    return render(
        request,
        "s_resource.html",
        context={
            "semester": semester,
            "resource": resource,
            "student_view": student_view,
            "lastGrades": student.getLastGrades(5),
            "validate": semester.department.validateYear(student),
            "usefulLinks": student.department.getUsefulLinks(),
        }
    )

@login_required
def ue(request, semester_id, ue_id):

    # Auth security
    user = request.user
    student = isStudent(user)
    if student == None:
        return redirect("login")

    # Query parameters
    semester = Semester.objects.filter(id=semester_id).first()
    ue = UE.objects.filter(id=ue_id).first()
    if semester == None or ue == None:
        return redirect("student:index")

    # Method body
    student_view = {}
    for resource in ue.getResources():
        student_view[resource] = {}
        for evaluation in resource.getEvaluations():
            student_view[resource][evaluation] = (
                evaluation.getNote(student),
                evaluation.getRanking(student),
                evaluation.getAverage(),
                evaluation.getMax(),
                evaluation.getMin()
            )

    return render(
        request,
        "s_ue.html",
        context={
            "semester": semester,
            "ue": ue,
            "student_view": student_view,
            "lastGrades": student.getLastGrades(5),
            "validate": semester.department.validateYear(student),
            "usefulLinks": student.department.getUsefulLinks(),
        }
    )

student/templates/index.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<h1>Bienvenue {{ user.last_name }} {{ user.first_name }} !</h1>
<h2>Vous étudiez dans l'établissement : {{ establishment }}</h2>

<div class="content">
    <form method="post">
        <select name="semestre" type="submit">
            {% for semester in semesters %}
            <option value="{{ semester }}">Semestre {{ forloop.counter }}</option>
            {% endfor %}
        </select>
    </form>
    <section class="ues">
        <div class="ue">
            <p>Nom de l'UE 1</p>
            <p>Note UE</p>
            <p>Classement</p>
        </div>
        <div class="ue">
            <p>Nom de l'UE 2</p>
            <p>Note UE</p>
            <p>Classement</p>
        </div>
        <div class="ue">
            <p>Nom de l'UE 2</p>
            <p>Note UE</p>
            <p>Classement</p>
        </div>
    </section>

    <aside>
        <section class="notes">
            <h3>Mes dernières notes</h3>
            <div class="note">
                <p>Nom note 1</p>
                <p>Note 1</p>
            </div>
            <div class="note">
                <p>Nom note 2</p>
                <p>Note 1</p>
            </div>
            <div class="note">
                <p>Nom note 3</p>
                <p>Note 1</p>
            </div>
        </section>
        <section class="links">
            <h3>Liens utiles</h3>
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}">{{ link.name }}</a>
            </div>
            {% endfor %}
        </section>
    </aside>
</div>

{% endblock %}

student/templates/notes.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">

    <h2>{{ semester }} {{ ue }}</h2>

    <section class="ues">
        {% for evaluation in evaluations %}
        <form action="">
            <div class="ue">
                <p><strong>{{ evaluation.name }}</strong></p>
                <p>Notes</p>
                <p>Moyenne</p>
                <p>Note max</p>
                <p>Note min</p>
            </div>
        </form>
        {% endfor %}
    </section>
    
</div>

<aside>
    <section class="notes">
        <h3>Mes dernières notes</h3>
        <div class="note">
            <p>Nom note 1</p>
            <p>Note 1</p>
        </div>
        <div class="note">
            <p>Nom note 2</p>
            <p>Note 1</p>
        </div>
    </section>
    <section class="links">
        <h3>Liens utiles</h3>
        {% for link in usefulLinks %}
        <div class="link">
            <img src="{% static link.file_path %}" alt="moodle" />
            <a href="{{ link.link }}">{{ link.name }}</a>
        </div>
        {% endfor %}
    </section>
</aside>

{% endblock %}

student/templates/resource.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <h1>Semestre {{ resource.semester.number }}</h1>
    <h2>{{ resource.name }}</h2>
    <div class="content">
        <div class="semester">
        {% for evaluation, stats in student_view.items %}
        <div class="styled-card resource">
            <h2 class="middle">{{ evaluation }}</h2>
            <div class="stats">
                <div>
                    <strong>Note</strong><br>{{ stats.0|default_if_none:"Non noté" }}
                </div>
                <div>
                    <strong>Moyenne</strong><br>{{ stats.2|default_if_none:"Aucune" }}
                </div>
            </div>
            <p></p>
            <p><strong>Classement</strong><br>{{ stats.1|default_if_none:"Non classé" }}</p>
            <div class="stats">
                <div>
                    <strong>Note maximale</strong><br>{{ stats.3|default_if_none:"Aucune" }}
                </div>
                <div>
                    <strong>Note minimale</strong><br>{{ stats.4|default_if_none:"Aucune" }}
                </div>
            </div>
        </div>
        {% endfor %}
        </div>
    </div>
</div>

<aside>
    <div class="aside-container">
        <div class="notes">
            <h3>Mes dernières notes</h3>
            {% for grade in lastGrades %}
            <div class="note">
                <p>{{ grade }}<br><em>{{ grade.note }}</em></p>
            </div>
            {% endfor %}
        </div>
        <div class="links">
            <h3>Liens utiles</h3>
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
        </div>
    </div>
</aside>

{% endblock %}

student/templates/s_index.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <h1>Bonjour {{ user.last_name }} {{ user.first_name }} !</h1>
    <h2>Vous étudiez dans l'établissement : {{ establishment }}</h2>

    <div class="selections">
        <select id="semesterSelection" name="semestre">
            {% for semester in student_view.keys %}
            <option value="{{ semester.id }}">{{ semester }}</option>
            {% endfor %}
        </select>
        <select id="viewSelection" name="view">
            <option value="resource">Ressource</option>
            <option value="ue">UE</option>
        </select>
    </div>

    <div class="content">
        {% for semester, resources_ues in student_view.items %}
        <div class="semester {{ semester.id }}">
            {% for resource, evaluations in resources_ues.0.items %}
            <div class="resource styled-card hoverable">
                <form class="auto" action="{% url 'student:resource' semester_id=semester.id resource_id=resource.id %}" method="post">
                    {% csrf_token %}
                    <h2><strong>{{ resource }}</strong><br>{{ resource.name }}</h2>
                    <p><strong>Note ressource</strong><br>{{ evaluations.1|default_if_none:"Non noté" }}</p>
                    <p><strong>Classement ressource</strong><br>{{ evaluations.2|default_if_none:"Non classé" }}</p>
                    <div class="styled-card evaluations">
                        <div class="title">Notes</div>
                        {% if not evaluations.0 %}
                        Aucunes notes.
                        {% else %}
                        <div class="carousel">
                            {% for evaluation, note in evaluations.0.items %}
                            <div class="evaluation carousel-item">
                                {{ evaluation.name }}
                                <br>
                                <em>{{ note|default_if_none:"Non noté" }}</em>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                </form>
            </div>
            {% endfor %}
            {% for ue, resources in resources_ues.1.items %}
            <div class="ue styled-card hoverable">
                <form class="auto" action="{% url 'student:ue' semester_id=semester.id ue_id=ue.id %}" method="post">
                    {% csrf_token %}
                    <h2><strong>UE {{ ue.number }}</strong></h2>
                    <p><strong>Note UE</strong><br>{{ resources.1|default_if_none:"Non noté" }}</p>
                    <p><strong>Classement UE</strong><br>{{ resources.2|default_if_none:"Non classé" }}</p>
                    {% for resource, evaluations in resources.0.items %}
                    <div class="styled-card evaluations">
                        <div class="title">{{ resource.name }}</div>
                        {% if not evaluations %}
                        Aucunes notes.
                        {% else %}
                        <div class="carousel">
                            {% for evaluation, note in evaluations.items %}
                            <div class="evaluation carousel-item">
                                {{ evaluation.name }}
                                <br>
                                <em>{{ note|default_if_none:"Non noté" }}</em>
                            </div>
                            {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    {% endfor %}
                </form>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>

<aside>
    <div class="aside-container styled-card">
        <!-- <div class="validate">
            <h3>Progression de l'année</h3>
            <p>{{ validate|yesno:"Vous validez l'année,Vous ne validez pas l'année,Indéterminable" }}</p>
        </div> -->
        <div class="notes">
            <h3>Mes dernières notes</h3>
            {% if not lastGrades %}
            <p>Aucune note.</p>
            {% else %}
            {% for grade in lastGrades %}
            <div class="note">
                <p>{{ grade }}<br><em>{{ grade.note }}</em></p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="links">
            <h3>Liens utiles</h3>
            {% if not usefulLinks %}
            Aucun lien utile.
            {% else %}
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</aside>

{% endblock %}

student/templates/s_resource.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <div class="history">
        <a href="{% url 'student:index'  %}"> < </a>
    </div>

    <h1>{{ semester }}<br>{{ resource }} </h1>
    <h2>{{ resource.name }}</h2>
    <div class="content">
        <h2>Liste des évaluations</h2>
        <div class="semester">
            {% for evaluation, stats in student_view.items %}
            <div class="resource styled-card hoverable">
                <h2 class="middle">{{ evaluation }}</h2>
                <div class="stats">
                    <div>
                        <strong>Note</strong><br>{{ stats.0|default_if_none:"Non noté" }}
                    </div>
                    <div>
                        <strong>Moyenne</strong><br>{{ stats.2|default_if_none:"Aucune" }}
                    </div>
                </div>
                <p><strong>Classement</strong><br>{{ stats.1|default_if_none:"Non classé" }}</p>
                <div class="stats">
                    <div>
                        <strong>Note minimale</strong><br>{{ stats.4|default_if_none:"Aucune" }}
                    </div>
                    <div>
                        <strong>Note maximale</strong><br>{{ stats.3|default_if_none:"Aucune" }}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<aside>
    <div class="aside-container styled-card">
        <!-- <div class="validate">
            <h3>Progression de l'année</h3>
            <p>{{ validate|yesno:"Vous validez l'année,Vous ne validez pas l'année,Indéterminable" }}</p>
        </div> -->
        <div class="notes">
            <h3>Mes dernières notes</h3>
            {% if not lastGrades %}
            Aucune note.
            {% else %}
            {% for grade in lastGrades %}
            <div class="note">
                <p>{{ grade }}<br><em>{{ grade.note }}</em></p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="links">
            <h3>Liens utiles</h3>
            {% if not usefulLinks %}
            Aucun lien utile.
            {% else %}
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</aside>

{% endblock %}

student/templates/s_ue.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <div class="history">
        <a href="{% url 'student:index'  %}"> < </a>
    </div>

    <h1>{{ semester }}<br>UE {{ semester.number }}.{{ ue.number }}</h1>
    <h2>{{ ue.name }}</h2>
    <div class="content">
        <h2>Liste des UEs</h2>
        <div class="ue_semester">
            {% for resource, evaluations in student_view.items %}
            <div class="ue_resource carousel-container styled-card">
                <h2 class="middle">{{ resource }}</h2>
                {% if not evaluations %}
                Aucune note.
                {% else %}
                <div class="ue_evaluations carousel">
                    {% for evaluation, stats in evaluations.items %}
                    <div class="ue_evaluation carousel-item styled-card hoverable">
                        <h2 class="middle">{{ evaluation }}</h2>
                        <div class="stats">
                            <div>
                                <strong>Note</strong>
                                <br>
                                {{ stats.0|default_if_none:"Non noté" }}
                            </div>
                            <div>
                                <strong>Moyenne</strong>
                                <br>
                                {{ stats.2|default_if_none:"Aucune" }}
                            </div>
                        </div>
                        <p><strong>Classement</strong>
                            <br>
                            {{ stats.1|default_if_none:"Non classé" }}</p>
                        <div class="stats">
                            <div>
                                <strong>Note minimale</strong><br>{{ stats.4|default_if_none:"Aucune" }}
                            </div>
                            <div>
                                <strong>Note maximale</strong><br>{{ stats.3|default_if_none:"Aucune" }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<aside>
    <div class="aside-container styled-card">
        <!-- <div class="validate">
            <h3>Progression de l'année</h3>
            <p>{{ validate|yesno:"Vous validez l'année,Vous ne validez pas l'année,Indéterminable" }}</p>
        </div> -->
        <div class="notes">
            <h3>Mes dernières notes</h3>
            {% if not lastGrades %}
            Aucune note.
            {% else %}
            {% for grade in lastGrades %}
            <div class="note">
                <p>{{ grade }}<br><em>{{ grade.note }}</em></p>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="links">
            <h3>Liens utiles</h3>
            {% if not usefulLinks %}
            Aucun lien utile.
            {% else %}
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</aside>

{% endblock %}