GestionBUT/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('accounts/', include("accounts.urls")),
    path('student/', include("student.urls")),
    path('professor/', include("professor.urls")),
    path('administrator/', include("administrator.urls")),
]

urlpatterns += staticfiles_urlpatterns()

main/urls.py
from django.urls import path
from main.views import index

app_name = 'main'

urlpatterns = [
    path('', index, name="index"),
]

professor/urls.py
from django.urls import path
from professor.views import *

app_name = 'professor'

urlpatterns = [
    # http://domain/professor/
    path('', index, name="index"),

    # http://domain/professor/1/
    path('<department_id>/', department, name="department"),

    # http://domain/professor/1/1/
    path('<department_id>/<resource_id>/', resource, name="resource"),

    # http://domain/professor/createEvaluation/1/1/ (no template)
    path('createEvaluation/<department_id>/<resource_id>/', createEvaluation, name="createEvaluation"),

    # http://domain/professor/editEvaluation/1/1/1/ (no template)
    path('editEvaluation/<department_id>/<resource_id>/<evaluation_id>/', editEvaluation, name="editEvaluation"),

    # http://domain/professor/deleteEvaluation/1/1/1/ (no template)
    path('deleteEvaluation/<department_id>/<resource_id>/<evaluation_id>/', deleteEvaluation, name="deleteEvaluation"),
]

professor/views.py
from django.shortcuts import render, redirect
from django.template.defaulttags import register
from django.contrib.auth.decorators import login_required

from main.models import *
from main.views import isProfessor, isStudent

# Filters (methods) for templates

@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)

@register.filter
def get_float(float):
    if (float == None):
        return ""
    return str(float).replace(",", ".")




@login_required
def index(request):

    # Auth security
    user = request.user
    professor = isProfessor(user)
    if professor == None:
        return redirect("login")

    # Method body
    professor_view = {}
    for establishment in professor.getEtablishments():
        professor_view[establishment] = {}
        for department in establishment.getDepartments():
            professor_view[establishment][department] = {}
            for semester in department.getSemesters():
                professor_view[establishment][department][semester] = semester.getProfessorResources(professor)

    return render(
        request,
        "p_index.html",
        context={
            "professor_view": professor_view
        }
    )

@login_required
def department(request, department_id):

    # Auth security
    user = request.user
    professor = isProfessor(user)
    if professor == None:
        return redirect("login")

    # Query parameters
    department = Department.objects.filter(id=department_id).first()
    if department == None:
        return redirect("professor:index")

    # Method body
    professor_view = {}
    professor_resources = {}
    for semester in department.getSemesters():
        professor_view[semester] = {}
        professor_resources[semester] = []
        for resource in semester.getResources():
            professor_view[semester][resource] = {}
            for evaluation in resource.getEvaluations():
                professor_view[semester][resource][evaluation] = {}
                for grade in evaluation.getGrades():
                    professor_view[semester][resource][evaluation][grade.student] = grade.note
        for resource in semester.getProfessorResources(professor):
            professor_resources[semester].append(resource)

    return render(
        request,
        "p_department.html",
        context = {
            "students": department.getStudents(),
            "professor_view": professor_view,
            "professor_resources": professor_resources,
            "department": department,
            "usefulLinks": department.getUsefulLinks(),
        }
    )

@login_required
def resource(request, department_id, resource_id):

    # Auth security
    user = request.user
    professor = isProfessor(user)
    if professor == None:
        return redirect("login")

    # Query parameters
    department = Department.objects.filter(id=department_id).first()
    resource = Resource.objects.filter(id=resource_id).first()
    if department == None:
        return redirect("professor:index")
    elif resource == None:
        return redirect("professor:department", department_id=department_id)

    # Method body
    professor_view = {}
    grades = {}
    for evaluation in resource.getEvaluations():
        grades[evaluation] = {}
        for grade in evaluation.getGrades():
            grades[evaluation][grade.student] = grade.note
        professor_view[evaluation] = (
            evaluation.getAverage(),
            evaluation.getMax(),
            evaluation.getMin(),
        )

    return render(
        request,
        "p_resource.html",
        context= {
            "professor_view": professor_view,
            "grades": grades,
            "department": department,
            "resource": resource,
            "usefulLinks": department.getUsefulLinks(),
        }
    )

@login_required
def createEvaluation(request, department_id, resource_id):

    # Auth security
    user = request.user
    professor = isProfessor(user)
    if professor == None:
        return redirect("main:index")

    # Query parameters
    department = Department.objects.filter(id=department_id).first()
    resource = Resource.objects.filter(id=resource_id).first()
    if request.method != "POST" or department == None:
        return redirect("professor:index")
    elif resource == None or resource not in professor.getResources(department):
        return redirect("professor:department", department_id=department.id)

    # Method body
    post = request.POST
    if "name" in post and "max_note" in post and "coef" in post and "group" in post:
        name = post.get("name")
        max_note = int(post.get("max_note"))
        coef = float(post.get("coef"))
        str_group = post.get("group")
        group = Group.objects.filter(id=int(str_group)).first()
        if name != "" and str_group != "none" and group != None:
            evaluation = Evaluation(name=name, max_note=max_note, coef=coef, professor=professor, resource=resource, group=group)
            evaluation.save()
            for str_student, note in post.items():
                if "note " + str_group in str_student:
                    user_id = int(str_student.split(" ")[2])
                    student = isStudent(user_id)
                    if student == None: continue
                    grade = Grade(evaluation=evaluation, student=student, note=float(note) if note != '' else None)
                    grade.save()

    return redirect("professor:department", department_id=department_id)

@login_required
def editEvaluation(request, department_id, resource_id, evaluation_id):

    # Auth security
    user = request.user
    professor = isProfessor(user)
    if professor == None:
        return redirect("main:index")

    # Query parameters
    department = Department.objects.filter(id=department_id).first()
    resource = Resource.objects.filter(id=resource_id).first()
    evaluation = Evaluation.objects.filter(id=evaluation_id).first()
    if request.method != "POST" or department == None:
        return redirect("professor:index")
    elif resource == None or resource not in professor.getResources(department) or evaluation == None:
        return redirect("professor:department", department_id=department.id)

    # Method body
    post = request.POST
    if "group" in post and "coef" in post:
        str_group = post.get("group")
        group = Group.objects.filter(id=str_group).first()
        coef = float(post.get("coef"))
        if group != None:
            evaluation.group = group
            evaluation.coef = coef
            evaluation.save()
            for str_student, note in post.items():
                if "note " + str_group in str_student:
                    user_id = int(str_student.split(" ")[2])
                    student = isStudent(user_id)
                    if student == None: continue
                    note = float(note) if note != '' else None
                    grade = evaluation.getGrade(student)
                    if grade != None:
                        grade.note = note
                        grade.save()
                    else:
                        grade = Grade(evaluation=evaluation, student=student, note=note)
                        grade.save()

    return redirect("professor:department", department_id=department_id)

@login_required
def deleteEvaluation(request, department_id, resource_id, evaluation_id):

    # Auth security
    user = request.user
    professor = isProfessor(user)
    if professor == None:
        return redirect("main:index")

    # Query parameters
    department = Department.objects.filter(id=department_id).first()
    resource = Resource.objects.filter(id=resource_id).first()
    evaluation = Evaluation.objects.filter(id=evaluation_id).first()
    if request.method != "POST" or department == None:
        return redirect("professor:index")
    elif resource == None or resource not in professor.getResources(department) or evaluation == None:
        return redirect("professor:department", department_id=department.id)

    # Method body
    evaluation.delete()

    return redirect("professor:department", department_id=department_id)

professor/templates/department.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <h1>{{ department.establishment }}<br>Département {{ department }}</h1>

    <select id="selection" name="semestre">
        {% for semester in professor_view.keys %}
        <option value="{{ semester.id }}">Semestre {{ semester.number }}</option>
        {% endfor %}
    </select>

    {% for semester, resources in professor_view.items %}
    {% for resource in resources.keys %}
    <div class="modal {{ resource.id }}">
        <div class="modal-content">
            <h2>Ajouter une note</h2>
            {{ resource }}
            <form action="{% url 'professor:createNote' department_id=department.id resource_id=resource.id %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <label for="name">Nom de l'évaluation</label>
                    <input type="text" name="name" id="name" required>
                </div>
                <div class="input">
                    <select class="group" name="group">
                        <option value="none" selected>Veuillez choisir un groupe</option>
                        {% for group in department.getGroups %}
                        <option value="{{ group.id }}">{{ group.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% for group in department.getGroups %}
                <div class="students {{ group.id }}">
                    {% for student in group.students.all %}
                    <div>{{ student.id.last_name }} {{ student.id.first_name }}</div>
                    <input type="number" name="note {{ group.id }} {{ student.id.id }}" step="any">
                    {% endfor %}
                </div>
                {% endfor %}
                <button class="modal-button">Ajouter</button>
            </form>
        </div>
    </div>
    {% endfor %}
    {% endfor %}

    <div class="content">
        {% for semester, resources in professor_view.items %}
        <div class="semester {{ semester.id }}">
            {% for resource, evaluations in resources.items %}
            <div class="styled-card resource">
                <h2>{{ resource }}</h2>
                <button class="resource-button {{ resource.id }}">Ajouter une évaluation</button>
                {% if evaluations %}
                <div class="styled-card evaluations">
                    <strong>Notes</strong>
                    {% for evaluation in evaluations %}
                    <div class="evaluation">{{ evaluation }} - {{ evaluation.professor }}</div>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>

<aside>
    <div class="aside-container">
        <div class="links">
            <h3>Liens utiles</h3>
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
        </div>
    </div>
</aside>

{% endblock %}

professor/templates/p_department.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <div class="history">
        <a href="{% url 'professor:index'  %}"> < </a>
    </div>

    <h1>{{ department.establishment }}<br>{{ department }}</h1>

    <select id="semesterSelection" name="semestre">
        {% for semester in professor_view.keys %}
        <option value="{{ semester.id }}">Semestre {{ semester.number }}</option>
        {% endfor %}
    </select>

    <div class="content">
        <h2>Liste des ressources</h2>
        {% for semester, resources in professor_view.items %}
        <table class="grid-semester {{ semester.id }}">
            <thead>
                <tr>
                    <th class="grid-resource-id">Ressource</th>
                    <th class="grid-resource-name">Nom</th>
                    <th class="grid-resource-evals">Evaluations</th>
                </tr>
            </thead>
            <tbody>
                {% for resource, evaluations in resources.items %}
                <tr>
                    <td class="middle">R{{ resource.semester.number }}.{{ resource.number }}</td>
                    <td style="white-space: nowrap;"><a href="{% url 'professor:resource' department_id=department.id resource_id=resource.id %}">{{ resource.name }}</a></td>
                    <td>
                        <div class="grid-evaluations">
                            {% if resource in professor_resources|get_item:semester %}
                            <div id="add_evaluation" class="add_grid-evaluation {{ resource.id }} grid-evaluation styled-card">+</div>
                            {% endif %}
                            {% for evaluation in evaluations %}
                            <div class="grid-evaluation {{ evaluation.id }} styled-card">{{ evaluation }}</div>
                            {% endfor %}
                        </div>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endfor %}

        <h2>Liste des étudiants</h2>
        <div class="search input styled-card">
            <input id="student_search" type="text" placeholder="Recherche par le nom...">
        </div>
        <div class="grid-students">
            {% for student in students %}
            <div class="student {{ student.id.id }} styled-card">
                {{ student.getFullName }}
            </div>
            {% endfor %}
        </div>

        <!-- {% for semester, resources in professor_view.items %}
        <div class="semester {{ semester.id }}">
            {% for resource, evaluations in resources.items %}
            <div class="resource styled-card hoverable">
                <form action="{% url 'professor:resource' department_id=department.id resource_id=resource.id %}" class="auto" method="post">
                    {% csrf_token %}
                    <h2><strong>{{ resource }}</strong></h2>
                    <p>{{ resource.name }}</p>
                    <div class="styled-card evaluations">
                        <div class="title">Notes</div>
                        {% if not evaluations %}
                        Aucune note.
                        {% else %}
                        {% for evaluation in evaluations %}
                        <div>{{ evaluation }} - {{ evaluation.professor }}</div>
                        {% endfor %}
                        {% endif %}
                    </div>
                </form>
            </div>
            {% endfor %}
        </div>
        {% endfor %} -->
    </div>

    {% for student in students %}
    <div class="modal student {{ student.id.id }}">
        <div class="modal-content">
            <h2>{{ student.getFullName }}</h2>
            <div class="info-card">
                <div class="info">
                    <p>Identifiant</p>
                    <p class="data">{{ student.id.username }}</p>
                </div>
                <div class="info">
                    <p>Email</p>
                    <p class="data">{{ student.id.email }}</p>
                </div>
            </div>
            <table class="grid-semester">
                <thead>
                    <tr>
                        <th class="grid-resource-id">Ressource</th>
                        <th class="grid-resource-name">Nom</th>
                        <th class="grid-resource-evals">Evaluations</th>
                    </tr>
                </thead>
                <tbody>
                    {% for resource in student.getResources %}
                    <tr>
                        <td class="middle">R{{ resource.semester.number }}.{{ resource.number }}</td>
                        <td style="white-space: nowrap;">
                            <a href="{% url 'professor:resource' department_id=department.id resource_id=resource.id %}">{{ resource.name }}</a>
                        </td>
                        <td>
                            <div class="grid-evaluations">
                                {% for evaluation in resource.getEvaluations %}
                                <div class="grid-evaluation middle styled-card">{{ evaluation }}<br>{{ professor_view|get_item:resource.semester|get_item:resource|get_item:evaluation|get_item:student }}</div>
                                {% endfor %}
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endfor %}

    {% for semester, resources in professor_view.items %}
    {% for resource, evaluations in resources.items %}
    {% for evaluation, grades in evaluations.items %}
    <div class="modal {{ evaluation.id }}">
        <div class="modal-content">
            <div class="modal-content-header">
                <h2>Modifier une note</h2>
                <form action="{% url 'professor:deleteEvaluation' department_id=department.id resource_id=resource.id evaluation_id=evaluation.id %}" method="post">
                    {% csrf_token %}
                    <button class="delete-button hoverable">Supprimer</button>
                </form>
            </div>
            <p>{{ evaluation }}</p>
            <form action="{% url 'professor:editEvaluation' department_id=department.id resource_id=resource.id evaluation_id=evaluation.id %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <label for="max_note">Note maximale</label>
                    <input type="number" id="max_note" value="{{ evaluation.max_note }}" disabled>
                </div>
                <div class="input">
                    <label for="coef">Coefficient</label>
                    <input type="number" name="coef" id="coef" step="0.1" value="{{ evaluation.coef|get_float }}" min="0.0" required>
                </div>
                <div class="input">
                    <select id="group" class="group" name="group">
                        {% for group in department.getGroups %}
                        <option value="{{ group.id }}" {% if evaluation.group.id == group.id %}selected{% endif %}>{{ group.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% for group in department.getGroups %}
                <div class="students {{ group.id }}">
                    {% for student in group.students.all %}
                    <div>{{ student.id.last_name }} {{ student.id.first_name }}</div>
                    <input type="number" name="note {{ group.id }} {{ student.id.id }}" value="{{ grades|get_item:student|get_float }}" step="0.01">
                    {% endfor %}
                </div>
                {% endfor %}
                <button class="modal-button hoverable">Confirmer</button>
            </form>
        </div>
    </div>
    {% endfor %}
    <div class="modal add_grid-evaluation {{ resource.id }}">
        <div class="modal-content">
            <h2>{{ resource }} : Ajouter une évaluation</h2>
            <form action="{% url 'professor:createEvaluation' department_id=department.id resource_id=resource.id %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <label for="import_evaluation">Importer une note</label>
                    <input type="file" id="import_evaluation" class="import_evaluation">
                </div>
                <div class="input">
                    <label for="name">Nom de l'évaluation</label>
                    <input type="text" name="name" id="name" required>
                </div>
                <div class="input">
                    <label for="max_note">Note maximale</label>
                    <input type="number" name="max_note" id="max_note" step="1" value="20" min="1" required>
                </div>
                <div class="input">
                    <label for="coef">Coefficient</label>
                    <input type="number" name="coef" id="coef" step="0.1" value="1.0" min="0.0" required>
                </div>
                <div class="input">
                    <select class="group" name="group">
                        <option value="none" selected>Veuillez choisir un groupe</option>
                        {% for group in department.getGroups %}
                        <option value="{{ group.id }}">{{ group.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% for group in department.getGroups %}
                <div class="students {{ group.id }}">
                    {% for student in group.students.all %}
                    <div>{{ student.id.last_name }} {{ student.id.first_name }}</div>
                    <input type="number" name="note {{ group.id }} {{ student.id.id }}" step="0.1">
                    {% endfor %}
                </div>
                {% endfor %}
                <button class="modal-button hoverable">Ajouter</button>
            </form>
        </div>
    </div>
    {% endfor %}
    {% endfor %}
</div>

<aside>
    <div class="aside-container styled-card">
        <div class="links">
            <h3>Liens utiles</h3>
            {% if not usefulLinks %}
            Aucun lien utile.
            {% else %}
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</aside>

{% endblock %}

professor/templates/p_index.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper">
    <h1>Bonjour {{ user.first_name }} {{ user.last_name }} !</h1>

    <select id="establishmentSelection" name="establishment">
        {% for establishment in professor_view.keys %}
        <option value="{{ establishment.id }}">{{ establishment }}</option>
        {% endfor %}
    </select>

    <div class="content">
        <h2>Liste des départements</h2>
        {% for establishment, departments in professor_view.items %}
        <div class="establishment {{ establishment.id }}">
            {% for department, semesters in departments.items %}
            <div class="department styled-card hoverable">
                <form action="{% url 'professor:department' department_id=department.id %}" class="auto" method="post">
                    {% csrf_token %}
                    <h2 class="middle">{{ department }}</h2>
                    {% if not semesters %}
                    <p class="middle">Aucun semestre</p>
                    {% else %}
                    <div class="semesters">
                        {% for semester, resources in semesters.items %}
                        {% if resources %}
                        <div class="styled-card semester">
                            <h2>Semestre {{ semester.number }}</h2>
                            <div class="resources">
                                {% for resource in resources %}
                                <div class="resource">
                                    <p><strong>{{ resource }}</strong><br>{{ resource.name }}</p>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                    {% endif %}
                </form>
            </div>
            {% endfor %}
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

professor/templates/p_resource.html
{% extends 'head.html' %}
{% load static %}
{% block content %}

<div class="wrapper left-side">
    <div class="history">
        <a href="{% url 'professor:department' department_id=department.id %}"> < </a>
    </div>

    <h1>{{ semester }}<br>{{ resource }} </h1>
    <h2>{{ resource.name }}</h2>

    {% for evaluation in professor_view %}
    <div class="modal {{ evaluation.id }}">
        <div class="modal-content">
            <h2>Modifier une note</h2>
            <form action="{% url 'professor:deleteEvaluation' department_id=department.id resource_id=resource.id evaluation_id=evaluation.id %}" method="post">
                {% csrf_token %}
                <button class="delete-button hoverable">Supprimer</button>
            </form>
            <p>{{ evaluation }}</p>
            <form action="{% url 'professor:editEvaluation' department_id=department.id resource_id=resource.id evaluation_id=evaluation.id %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <select id="group" class="group" name="group">
                        {% for group in department.getGroups %}
                        <option value="{{ group.id }}" {% if evaluation.group.id == group.id %}selected{% endif %}>{{ group.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% for group in department.getGroups %}
                <div class="students {{ group.id }}">
                    {% for student in group.students.all %}
                    <div>{{ student.id.last_name }} {{ student.id.first_name }}</div>
                    <input type="number" name="note {{ group.id }} {{ student.id.id }}" value="{{ grades|get_item:evaluation|get_item:student|get_float }}" step="0.1">
                    {% endfor %}
                </div>
                {% endfor %}
                <button class="modal-button hoverable">Modifier</button>
            </form>
        </div>
    </div>
    {% endfor %}
    <div class="modal add_evaluation {{ resource.id }}">
        <div class="modal-content">
            <h2>Ajouter une évaluation</h2>
            <form action="{% url 'professor:createEvaluation' department_id=department.id resource_id=resource.id %}" method="post">
                {% csrf_token %}
                <div class="input">
                    <label for="name">Importer une note</label>
                    <input type="file" id="import_evaluation" class="import_evaluation">
                </div>
                <div class="input">
                    <label for="name">Nom de l'évaluation</label>
                    <input type="text" name="name" id="name" required>
                </div>
                <div class="input">
                    <label for="max_note">Note maximale</label>
                    <input type="number" name="max_note" id="max_note" step="1" value="20" min="1" required>
                </div>
                <div class="input">
                    <label for="coef">Coefficient</label>
                    <input type="number" name="coef" id="coef" step="0.1" value="1.0" min="0.0" required>
                </div>
                <div class="input">
                    <select class="group" name="group">
                        <option value="none" selected>Veuillez choisir un groupe</option>
                        {% for group in department.getGroups %}
                        <option value="{{ group.id }}">{{ group.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                {% for group in department.getGroups %}
                <div class="students {{ group.id }}">
                    {% for student in group.students.all %}
                    <div>{{ student.id.last_name }} {{ student.id.first_name }}</div>
                    <input type="number" name="note {{ group.id }} {{ student.id.id }}" step="0.1">
                    {% endfor %}
                </div>
                {% endfor %}
                <button class="modal-button hoverable">Ajouter</button>
            </form>
        </div>
    </div>

    <div class="content">
        <h2>Liste des évaluations</h2>
        <div class="semester">
            <div id="add_evaluation" class="add_evaluation {{ resource.id }} plus styled-card hoverable">+</div>
            {% for evaluation, stats in professor_view.items %}
            <div class="evaluation {{ evaluation.id }} styled-card hoverable">
                <h2 class="middle">{{ evaluation }}</h2>
                <p><strong>Moyenne</strong><br>{{ stats.0|default_if_none:"Aucune" }}</p>
                <div class="stats">
                    <div>
                        <strong>Note minimale</strong><br>{{ stats.2|default_if_none:"Aucune" }}
                    </div>
                    <div>
                        <strong>Note maximale</strong><br>{{ stats.1|default_if_none:"Aucune" }}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<aside>
    <div class="aside-container styled-card">
        <div class="links">
            <h3>Liens utiles</h3>
            {% if not usefulLinks %}
            Aucun lien utile.
            {% else %}
            {% for link in usefulLinks %}
            <div class="link">
                <img src="{% static link.file_path %}" alt="moodle" />
                <a href="{{ link.link }}" target="_blank">{{ link.name }}</a>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</aside>

{% endblock %}